name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
      - testing-workflow

jobs:
  build:
    runs-on: ubuntu-latest # Specify the runner environment

    strategy:
      matrix:
        include:
          #- tag_prefix: amd
          #  dockerfile_path: ./Dockerfile_amd
          - tag_prefix: nvidia
            dockerfile_path: ./Dockerfile_nvidia

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Action to checkout your code

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} # Use your GitHub Secrets
      
      - name: Build Image
        uses: docker/build-push-action@v5
        with:
          context: . # Path to the Dockerfile context (usually the root of your repo)
          file: ${{ matrix.dockerfile_path }} # Path to your Dockerfile
          push: false # Do not push yet
          tags: test-image
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/rod:${{ matrix.tag_prefix }}-latest
          cache-to: type=inline

      - name: Run App
        run: |
          docker run -d --name app_test -p 5000:5000 test-image
          echo "Waiting for app to start..."
          sleep 10

      - name: Run Tests
        run: |
          echo "Running tests..."
          pytest tests/ -v --disable-warnings --junitxml=report.xml

      - name: Add Test Results
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Test Results
          path: report.xml
          reporter: java-junit

      - name: Stop App
        run: |
          echo "Stopping the application..."
          docker stop app_test
          docker rm app_test

      - name: Tag and push image
        if: success()
        run: |
          docker tag test-image ${{ secrets.DOCKER_USERNAME }}/rod:${{ matrix.tag_prefix }}-latest
          docker tag test-image ${{ secrets.DOCKER_USERNAME }}/rod:${{ matrix.tag_prefix }}-${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/rod:${{ matrix.tag_prefix }}-latest
          docker push ${{ secrets.DOCKER_USERNAME }}/rod:${{ matrix.tag_prefix }}-${{ github.sha }}

